// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	"tuwei/babel_fish/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/users",
				Handler: UserHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/tasks",
				Handler: CreateTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tasks/:id",
				Handler: GetTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tasks/:id/download",
				Handler: DownloadTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tasks/:id/translate",
				Handler: TranslateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
